 
NAME = polymorphism 

SRCS = main.cpp Animal.cpp Dog.cpp Cat.cpp
 
HEADERS = Animal.hpp Dog.hpp Cat.hpp
 
COMPILER = c++
 
FLAGS = -Wall -Wextra -Werror
 
all: $(NAME)
 
$(NAME): $(SRCS) $(HEADERS)
	$(COMPILER) $(FLAGS) $(SRCS) -o $(NAME)
 
clean:
	rm -rf $(NAME)
 
fclean: clean
 
re: fclean all
 
.PHONY: all clean fclean re

